name: env_subsetting
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=4.2.0=py312h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h5eee18b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py312h06a4308_0
  - babel=2.11.0=py312h06a4308_0
  - beautifulsoup4=4.12.2=py312h06a4308_0
  - brotli-python=1.0.9=py312h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py312h06a4308_0
  - cffi=1.16.0=py312h5eee18b_0
  - comm=0.2.1=py312h06a4308_0
  - debugpy=1.6.7=py312h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=h6a678d5_0
  - ipykernel=6.28.0=py312h06a4308_0
  - ipython=8.20.0=py312h06a4308_0
  - jedi=0.18.1=py312h06a4308_1
  - jinja2=3.1.3=py312h06a4308_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter-lsp=2.2.0=py312h06a4308_0
  - jupyter_client=8.6.0=py312h06a4308_0
  - jupyter_core=5.5.0=py312h06a4308_0
  - jupyter_events=0.8.0=py312h06a4308_0
  - jupyter_server=2.10.0=py312h06a4308_0
  - jupyter_server_terminals=0.4.4=py312h06a4308_1
  - jupyterlab=4.0.11=py312h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py312h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - mistune=2.0.4=py312h06a4308_0
  - nbclient=0.8.0=py312h06a4308_0
  - nbconvert=7.10.0=py312h06a4308_0
  - nbformat=5.9.2=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py312h06a4308_0
  - notebook-shim=0.2.3=py312h06a4308_0
  - openssl=3.0.13=h7f8727e_0
  - overrides=7.4.0=py312h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=23.3.1=py312h06a4308_0
  - prometheus_client=0.14.1=py312h06a4308_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py312h06a4308_1
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.2=h996f2a0_0
  - python-fastjsonschema=2.16.2=py312h06a4308_0
  - python-json-logger=2.0.7=py312h06a4308_0
  - pyyaml=6.0.1=py312h5eee18b_0
  - pyzmq=25.1.2=py312h6a678d5_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py312h06a4308_0
  - requests=2.31.0=py312h06a4308_1
  - rfc3339-validator=0.1.4=py312h06a4308_0
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - rpds-py=0.10.6=py312hb02cf49_0
  - send2trash=1.8.2=py312h06a4308_0
  - setuptools=68.2.2=py312h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py312h06a4308_0
  - soupsieve=2.5=py312h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py312h06a4308_0
  - tinycss2=1.2.1=py312h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - traitlets=5.7.1=py312h06a4308_0
  - typing_extensions=4.9.0=py312h06a4308_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312h06a4308_2
  - websocket-client=0.58.0=py312h06a4308_4
  - wheel=0.41.2=py312h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - aiobotocore==2.12.2
      - aiohttp==3.9.3
      - aioitertools==0.11.0
      - aiosignal==1.3.1
      - asciitree==0.3.3
      - attrs==23.2.0
      - bleach==6.1.0
      - bokeh==3.4.0
      - botocore==1.34.51
      - bottleneck==1.3.8
      - cartopy==0.23.0
      - cftime==1.6.3
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cloudpickle==3.0.0
      - colorcet==3.1.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - dask==2024.4.1
      - dask-expr==1.0.11
      - datashader==0.16.0
      - distributed==2024.4.1
      - fasteners==0.19
      - fiona==1.9.6
      - flox==0.9.6
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - future==1.0.0
      - geopandas==0.14.3
      - geoviews==1.12.0
      - h5netcdf==1.3.0
      - h5py==3.11.0
      - holoviews==1.18.3
      - idna==3.6
      - jmespath==1.0.1
      - kiwisolver==1.4.5
      - linkify-it-py==2.0.3
      - llvmlite==0.42.0
      - locket==1.0.0
      - lz4==4.3.3
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - mdit-py-plugins==0.4.0
      - mdurl==0.1.2
      - msgpack==1.0.8
      - multidict==6.0.5
      - multipledispatch==1.0.0
      - netcdf4==1.6.5
      - numba==0.59.1
      - numbagg==0.8.1
      - numcodecs==0.12.1
      - numpy==1.26.4
      - numpy-groupies==0.10.2
      - numpy-indexed==0.3.7
      - opt-einsum==3.3.0
      - packaging==24.0
      - pandas==2.2.1
      - panel==1.4.1
      - param==2.1.0
      - partd==1.4.1
      - pillow==10.3.0
      - platformdirs==4.2.0
      - pooch==1.8.1
      - psutil==5.9.8
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - pyct==0.5.0
      - pyparsing==3.1.2
      - pyproj==3.6.1
      - pyshp==2.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyviz-comms==3.0.2
      - s3fs==2024.3.1
      - scipy==1.13.0
      - shapely==2.0.3
      - sortedcontainers==2.4.0
      - tblib==3.0.0
      - thalassa==0.4.5
      - toolz==0.12.1
      - tornado==6.4
      - tqdm==4.66.2
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - uc-micro-py==1.0.3
      - urllib3==2.0.7
      - wrapt==1.16.0
      - xarray==2024.3.0
      - xyzservices==2024.4.0
      - yarl==1.9.4
      - zarr==2.17.2
      - zict==3.0.0

