channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - ipython
  - jupyterlab
  - pandas
  - requests
  - pyyaml
  - beautifulsoup4
  - matplotlib-inline
  - pip:
      - aiobotocore
      - aiohttp
      - bokeh
      - cartopy
      - dask
      - datashader
      - distributed
      - fiona
      - flox
      - geopandas
      - geoviews
      - h5netcdf
      - h5py
      - holoviews
      - matplotlib
      - netcdf4
      - numba
      - numpy
      - panel
      - pyarrow
      - pyproj
      - s3fs
      - scipy
      - shapely
      - thalassa
      - xarray
      - zarr